#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import httpshell


def parse_command_line():
    parser = argparse.ArgumentParser(
        description="An interactive shell for issuing HTTP commands to a web server or REST API")

    parser.add_argument(
        "url",
        metavar="URL",
        help="url to connect to")

    parser.add_argument(
        "--version",
        action="version",
        version="{0} {1}".format("%(prog)s", httpshell.VERSION))

    return parser.parse_args()


def main():
    args = parse_command_line()
    shell = httpshell.HttpShell(args)
    shell.input_loop()


if __name__ == "__main__":
    main()
